version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skylink
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  laravel:
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=skylink
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

#   node:
#     build: ./node
#     working_dir: /usr/src/app
#     volumes:
#       - ./node:/usr/src/app
#     command: node server.js
#     ports:
#       - "3000:3000"
#     depends_on:
#       - redis

volumes:
  mysql_data:
